### ISSUE TITLE
Release TODO

### ISSUE THREAD

**Issue by rmcgibbo** [msmbuilder/msmbuilder#273]
- [x] Remove MSLDS code
- [x] Remove CUDA HMM?
- [x] Port HMM code to not depend on sklearn's hmm, which is deprecated.
- [ ] Remove or fix von Mises HMM
- [ ] Command line stuff...

cc @mpharrigan @schwancr
